version: 1.0.{build}
image: Ubuntu2204
branches:
  only:
  - master

# Set environment
environment:
  MLE_ROOT: /opt/MagicLantern

# Install dependencies
install:
- sh: >-
    sudo apt install -y python3-pip;
    sudo apt install -y libssl-dev;
    sudo apt install -y libffi-dev;
    sudo apt install -y python3-dev;
- sh: >-
    sudo mkdir $MLE_ROOT;
    git clone -q --branch=master https://github.com/magic-lantern-studio/mle-core-util.git /home/appveyor/projects/mle-core-util;
    cd /home/appveyor/projects/mle-core-util/util/linux/build;
    libtoolize;
    aclocal;
    automake --add-missing --ignore-deps;
    autoconf;
    ./configure;
    make;
    sudo MLE_ROOT=$MLE_ROOT make install
- sh: >-
    git clone -q --branch=master https://github.com/magic-lantern-studio/mle-core-math.git /home/appveyor/projects/mle-core-math;
    cd /home/appveyor/projects/mle-core-math/math/linux/libmlmath;
    libtoolize;
    aclocal;
    automake --add-missing --ignore-deps;
    autoconf;
    ./configure;
    make;
    sudo MLE_ROOT=$MLE_ROOT make install
- sh: >-
    git clone -q --branch=master https://github.com/magic-lantern-studio/mle-core-dwp.git /home/appveyor/projects/mle-core-dwp;
    cd /home/appveyor/projects/mle-core-dwp/DigitalWorkprint/lib/linux;
    libtoolize;
    aclocal;
    automake --add-missing --ignore-deps;
    autoconf;
    ./configure;
    make;
    sudo MLE_ROOT=$MLE_ROOT make install

# Custom script to build Digital Playprint components using autoconf tools.
build_script:
- sh: >-
    cd /home/appveyor/projects/mle-core-dpp/DigitalPlayprint/lib/linux;
    libtoolize;
    aclocal;
    automake --add-missing --ignore-deps;
    autoconf;
    ./configure;
    make;
    sudo MLE_ROOT=$MLE_ROOT make install
- sh: >-
    cd /home/appveyor/projects/mle-core-dpp/DigitalPlayprint/runtime/linux;
    libtoolize;
    aclocal;
    automake --add-missing --ignore-deps;
    autoconf;
    ./configure;
    make;
    sudo MLE_ROOT=$MLE_ROOT make install
- sh: >-
    cd /home/appveyor/projects/mle-core-dpp/DigitalPlayprint/master/linux/libDPPGen;
    libtoolize;
    aclocal;
    automake --add-missing --ignore-deps;
    autoconf;
    ./configure;
    make;
    sudo MLE_ROOT=$MLE_ROOT make install
- sh: >-
    cd /home/appveyor/projects/mle-core-dpp/DigitalPlayprint/master/linux/gentables;
    libtoolize;
    aclocal;
    automake --add-missing --ignore-deps;
    autoconf;
    ./configure;
    make;
    sudo MLE_ROOT=$MLE_ROOT make install
- sh: >-
    cd /home/appveyor/projects/mle-core-dpp/DigitalPlayprint/master/linux/gengroup;
    libtoolize;
    aclocal;
    automake --add-missing --ignore-deps;
    autoconf;
    ./configure;
    make;
    sudo MLE_ROOT=$MLE_ROOT make install
- sh: >-
    cd /home/appveyor/projects/mle-core-dpp/DigitalPlayprint/master/linux/genscene;
    libtoolize;
    aclocal;
    automake --add-missing --ignore-deps;
    autoconf;
    ./configure;
    make;
    sudo MLE_ROOT=$MLE_ROOT make install
- sh: >-
    cd /home/appveyor/projects/mle-core-dpp/DigitalPlayprint/master/linux/genmedia;
    libtoolize;
    aclocal;
    automake --add-missing --ignore-deps;
    autoconf;
    ./configure;
    make;
    sudo MLE_ROOT=$MLE_ROOT make install
- sh: >-
    cd /home/appveyor/projects/mle-core-dpp/DigitalPlayprint/master/linux/genmakefile;
    libtoolize;
    aclocal;
    automake --add-missing --ignore-deps;
    autoconf;
    ./configure;
    make;
    sudo MLE_ROOT=$MLE_ROOT make install
- sh: >-
    cd /home/appveyor/projects/mle-core-dpp/DigitalPlayprint/master/linux/genppscript;
    libtoolize;
    aclocal;
    automake --add-missing --ignore-deps;
    autoconf;
    ./configure;
    make;
    sudo MLE_ROOT=$MLE_ROOT make install
- sh: >-
    cd /home/appveyor/projects/mle-core-dpp/DigitalPlayprint/master/linux/gendpp;
    libtoolize;
    aclocal;
    automake --add-missing --ignore-deps;
    autoconf;
    ./configure --enable-python-integration;
    make;
    sudo MLE_ROOT=$MLE_ROOT make install
- sh: >-
    cd /home/appveyor/projects/mle-core-util/util/linux/build;
    sudo MLE_ROOT=$MLE_ROOT make uninstall;
    cd /home/appveyor/projects/mle-core-math/math/linux/libmlmath;
    sudo MLE_ROOT=$MLE_ROOT make uninstall;
    cd /home/appveyor/projects/mle-core-dwp/DigitalWorkprint/lib/linux;
    sudo MLE_ROOT=$MLE_ROOT make uninstall

# Custom script to create an .zip file containing the libDWP artifacts.
after_build:
- sh: >-
    cd /home/appveyor/projects/mle-core-dpp;
    7z a dpp.zip $MLE_ROOT

# Define artifacts to push to AppVeyor
artifacts:
- path: dpp.zip
  name: mle-core-dpp
